### PR TITLE
Add clear() to RelOptPlanner. PlannerImpl.transform() call clear().

### PR DESCRIPTION
**Pull request by jinfengni**
Hi Julian,

This is the code I modified in my local branch, which will clear the internal status of RelOptPlanner in the PlannerImpl.transform(). 

The reason for adding clear() is because we want to call transform() multiple times, and RelOptPlanner would hit problem during the second call of transform(), because it still has the status from the first call of transform(). 

Please take a look and see if this is the right fix to address the issue.  Thanks!

### CODE REVIEW

**Comment by jinfengni** [comment]
Travis shows the testcase fails at JdbcTest.testWithInsideWhereExists on oracle jdk7.

However, on my machine the testcase is successful on oracle jdk7.  Any idea why there would be different result ? 

......
Running net.hydromatic.optiq.test.JdbcTest
Tests run: 95, Failures: 0, Errors: 0, Skipped: 15, Time elapsed: 123.138 sec - in net.hydromatic.optiq.test.JdbcTest
.......

Results :

## Tests run: 1383, Failures: 0, Errors: 0, Skipped: 85

mvn -version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T09:37:52-08:00)
Maven home: /Applications/apache-maven-3.2.1
Java version: 1.7.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.2", arch: "x86_64", family: "mac"

**Comment by julianhyde** [comment]
I noticed those travis-CI failures too. It happened on all JDK versions, but not consistently. Meanwhile I ran the test 100 times on my machine and couldn't reproduce it. I think there's a concurrency issue that shows up on travis because it runs in a 1.5-core VM.

Commit https://github.com/julianhyde/optiq/commit/76665ad0c51be740be3c2f67324544de43e724cc fixed an issue with the list that was throwing the exception. It seems to have worked.

**Comment by julianhyde** [comment]
The pull request looks basically good. Can you add a test case that fails before the fix and succeeds after it?

**Comment by jinfengni** [comment]
Sure, I'll add a testcase.

**Pull request closed without merging**
