### PR TITLE
Add FrameworkContext and FrameworkConfig

### PR DESCRIPTION
**Pull request by jacques-n**
Allow RelOptCostFactory to be replaced.  Make getPlanner() cleaner by using configuration object and builder pattern.

### CODE REVIEW

**Comment by jacques-n** [comment]
This is WIP but wanted to get initial feedback.  Will wrap up shortly.

**Comment by jacques-n** [comment]
Updated to complete patch, let me know thoughts.  Thanks

**Comment by julianhyde** [comment]
Sorry I took so long to review this.

`FrameworkContext` should not live in `net.hydromatic.optiq.tools`, since it is used in several packages. Can you find a better name and place for it.

Regarding the name. The `Framework` would need to go, but you can keep `Context`. ("Context" is an over-used term, and there is already a `OptiqPrepare.Context`, but I see that `Context` is the term of art in dependency-injection, which is what this thing does.)

I suggest you make `StdFrameworkConfig` private (or at least package protected) and move `StdFrameworkConfig.newBuilder` to `Frameworks`. We don't want people to start depending on the "standard" config class.

And there is some crap to be cleaned up: '//' on the end of some lines; some broken javadoc (make sure `mvn site` works).

No need to rebase master - I checked and the latest merges just fine.

**Comment by jacques-n** [comment]
Julian, the extra slashes on the lines is a staylistic thing we've adopted in Drill.  It allows a user to format lines in a particular way such that automatic code formatting IDE leaves complex multiline statements alone.  I'd suggest we adopt in Optiq as well as the ability to cleanly format builder patterns while using IDE formatting allows developers to spend less time worried about code style.  Thoughts?

**Comment by julianhyde** [comment]
I can accept trailing `//` if used sparingly, as in this pull request. If it starts to become the norm then people need to fix their IDE.

**Pull request closed without merging**
