### PR TITLE
println statement interferes with sqlline output

### PR DESCRIPTION
**Pull request by cwensel**
just pointing this out, am sure its better off emitted through the logging interface

### CODE REVIEW

**Comment by julianhyde** [comment]
Agreed - we should always use logging rather than System.out or System.err.

I can't accept the patch. Too many whitespace changes.

What logging framework do you suggest?

**Comment by julianhyde** [comment]
Removed the println.

**Comment by cwensel** [comment]
no worries about accepting patches, I find them more useful for illustrative purposes.

Cascading uses slf4j for logging, this way the underlying platform can specify the actual implementation (log4j typically). 

But I see a few native logging interfaces directly in Optiq, happy to couple my code to those if they are a best practice.

**Comment by cwensel** [comment]
yes, I would say slf4j as the api, and log4j as the default implementation (or j.u.l to keep the default deps simple, maybe)

**Pull request closed without merging**
