### PR TITLE
Implement table functions.

### PR DESCRIPTION
**Pull request by vlsi**
The structure (number of columns) might depend on the input arguments that are provided as literals (see `JdbcTest.multiplicationTable`)

This PR moves [Public Morozov](http://en.wikipedia.org/wiki/Pavlik_Morozov) out of `RexImpTable`, so `ScalarFunctionImpl` and `TableFunctionImpl` can properly implement the required call via linq4j (see `ImplementableFunction`).

Not included in current pull request:
- Table functions that take cursor parameters. It fails with `CannotPlanException`, see `JdbcTest.testTableFunctionCursorInputs`.
- Costing model (i.e. the number of rows returned by a function, io cost, cpu cost)
- Collation model
- Table function based on a method that returns `Enumerable`. 
- Configurable null policy for user-defined functions (see `ScalarFunctionImpl.createImplementor`)

### CODE REVIEW

**Comment by julianhyde** [comment]
This is great work. It's how I intended to implement table-functions.

Can you add a test for table-functions included in a model? Something similar to JdbcTest.testTableMacroInModel.

I've made a few comments that need to be fixed, then I will merge.

**Comment by vlsi** [comment]
> Can you add a test for table-functions included in a model

Makes sense. Please find `testTableFunctionInModel` and `testStaticTableFunctionInModel`.

I've corrected other comments: removed javadocs from interface implementations, added a couple more `@Ignored` tests: `testTableFunctionNonNullableMustBeLiterals`, `testTableFunctionCursorInputs`, `testTableFunctionCursorsInputs`, etc

**Comment by vlsi** [comment]
As seen from previous implementation of `MethodTableMacro.apply` (e.g. https://github.com/julianhyde/optiq/blob/c53be95c507af375eaa213f75e3982e9e545fff3/core/src/main/java/net/hydromatic/optiq/impl/java/ReflectiveSchema.java#L314 ) there was an attempt to convert method-returning-enumerable to a table in reflective schema.

In fact it did not work, but let's assume it did. I do not elaborate this idea to avoid complication of the code. Table functions should to have a row type, physical element type, and it is not that easy to convert method return type (i.e. `Enumerable`) to rowtype+elementype.

**Comment by julianhyde** [comment]
Merged as https://github.com/julianhyde/optiq/commit/aa1f0983c126c23466deb990c96d6ff2dffd908c.

**Pull request closed without merging**
