### PR TITLE
expose properties via getter

### PR DESCRIPTION
**Pull request by cwensel**
here's some illustrative code I needed to get me going again.. 

the gist is having an opportunity to parse the jdbc connect string, yank out any key=value pairs, and push them out to downstream consumers in the planner.

I think some of my import optimizations may have leaked into the commit so feel free to close and duplicate etc..

### CODE REVIEW

**Comment by cwensel** [comment]
ugh, ok, so seems you can't make a pull request on a single commit... 

so i've added a commit that exemplifies changes needed for a usable dbunit test case. this gets me basic test functionality.

unfortunately dbunit barfs exceptions via the logger because it can't get what it wants from DatabaseMetaData before it punts to ResultSetMetaData. I can live with that for now.

**Comment by julianhyde** [comment]
I've added OptiqConnection.getProperties() in https://github.com/julianhyde/optiq/commit/e728c011645b6d18ef11ab2bfbdbc53e303a4954.

**Comment by julianhyde** [comment]
I've implemented DatabaseMetaData.getColumns() in https://github.com/julianhyde/optiq/commit/33258f7548fe8355a718d1b1b9a522cd41770259. Closing this pull request.

**Comment by cwensel** [comment]
ok, there was one more small change in that commit where ColumnMetaData#columnName was populated with the values used for ColumnMetaData#label.

**Pull request closed without merging**
