### PR TITLE
Improve window support for window aggregates

### PR DESCRIPTION
**Pull request by vlsi**
This is a work in progress for https://github.com/julianhyde/optiq/issues/274:
1) expressions in "preceding/following"
2) unbounded following

I guess parsing/sqltorel translation is done properly.

Todo:
 Implement `EnumerableWindowRel`, tests

### CODE REVIEW

**Comment by julianhyde** [comment]
Please fix checkstyle errors before I pull this. Please also rebase latest master (including https://github.com/julianhyde/optiq/commit/8157acaf1c9e3a7fa72b8bb353572261aa333d5a), since it's in a similar area.

**Comment by vlsi** [comment]
Here's rebased version.

Updates:
1) I've identified a bug with translation of constants: `JdbcTest.testWinAggConstantMultipleConstants`
The way `EnumerableWindowRel` hijack `inputPhysType` makes me cry since it breaks my `InputGetterImpl(inputs)`. I have not yet figured out the nice way to overcome this.
2) RANGE windows are not yet supported. We need some kind of binary search that would guarantee the result when multiple entries share the same value and we can't use java's built-in since it does not provide that.
3) I do not like the idea of `orderChanged` and `orderKeyStartIndex`. I would rather pass _two_ pairs of (translator + builder) to the aggregate impl. The first pair is to define variables _outside_ of window-loop, and the second pair is to define variables inside the window-loop.
What do you think?
From my point of view, this would enable usage of primitives even when computing window aggregates over nullable expressions (e.g. define `bool allNulls` and `int sum` locals when computing `sum(nullable_int)`).
This would solve `dense_rank` problem as well, so it can define `orderChanged` or whatever it requires with no impact on all the other window aggregates.

**Comment by julianhyde** [comment]
> The way EnumerableWindowRel hijack inputPhysType makes me cry

Are you referring to the line

``` java
inputPhysType = outputPhysType;
```

I don't remember why I did that. If there are multiple windows, it will either do something clever or do something stupid. Not sure which.

Feel free to change it.

> 2) RANGE windows are not yet supported. We need some kind of binary search that would guarantee the result when multiple entries share the same value and we can't use java's built-in since it does not provide that.

Or a sorted data structure such as a TreeMap.

There are a couple of algorithms for windowed aggregation. You can hash on partition key and use a priority queue on the order by key, or you can sort on partition key + order key. The former is attractive if there are lots of partitions with not many rows in each. The priority queue might be maintained incrementally, hence a tree-map or something.

It's worth doing a thought experiment how you would implement `NTILE` and `MEDIAN`. They might place additional requirements on your data structure.

> 3) I do not like the idea of orderChanged and orderKeyStartIndex.
> I think you're referring to methods on `AddInfo`. The idea of this interface was to allow us to supply extra information to user-defined aggregates in future without breaking compatibility. (If I hadn't done this, we'd have to keep on adding extra parameters to `implementAdd`.)

It's fine if the implementation of AddInfo is backed by multiple sources -- some supplying info for the current agg function (e.g. the accumulator), some for the current window, some for where we are in the traversal over the current window (e.g. are we on the first row, or the first row with a particular order key).

An agg fun shouldn't have to know the details of how the code generation is performed. I'd rather it didn't know, for instance, that the values in the window are stored in an array. I'm not saying we should do this, but if we've designed the agg function SPI right, we should be able to change the implementation from an array to a TreeMap without people having to rewrite their custom agg functions.

**Comment by vlsi** [comment]
> Or a sorted data structure such as a TreeMap.

I looked a bit into postgresql design of windowed aggregates, and they track window bounds in terms of "shrink and extend the window".
In other words, the implementation of the aggregate can reuse the data structure if the window is just extended by one row (e.g. rows unbounded preceding and current row).

This is orthogonal to current optiq's "calculate start and end and perform the for-aggregate-loop".

> An agg fun shouldn't have to know the details of how the code generation is performed

Agg framework should not decide for the agg function on the intermediate data structure used for the computation.
Agg function should be able to decide its own data structure for efficient computation.

**Comment by julianhyde** [comment]
FYI - I tried to merge this and got 4 failures and 7 errors in core. Remove the label "broken" when you want me to try again.

**Comment by vlsi** [comment]
I did not mean to merge it before CI gets green.
My intention was to get some feedback early.

> sort on partition key + order key
> The priority queue

Those kind of structures do not allow indexed access to the tuples (e.g. `lead`/`lag` functions).
`TreeMap` consumes more memory and creates lots of indirections (when compared to `ArrayList`), thus it is more like an overhead in our case.

I've browsed around PosgreSQL sources, and it turns out they do omit interesting cases: `elog(ERROR, "window frame with value offset is not implemented");`.

> I'd rather it didn't know, for instance, that the values in the window are stored in an array
> I agree. This kind of details should not leak to the agg function implementation. That is why I plan to use `RexToLixTranslator` as a context provider for the agg function. If agg function wants to get argument value, it calls `translate` with appropriate `RexInputRef`.

What I mean is as follows: agg function implementation creates storage for intermediate state in the given block (e.g. `long sum` and `boolean allNulls` for `sum(long)`) , updates the intermediate storage as new rows come by (e.g. when it is asked by `generateWindowLoop`), and returns the result when asked (in case of `sum(long)` this would be `allNulls ? (Long) null : sum`).

**Comment by julianhyde** [comment]
I don't have a strong opinion about a particular data structure. Quite the reverse - I'd like win agg functions to not have to know the details of how the "window" is implemented. Then we can slot in better implementations of window over time.

One idea. Introduce internal winagg functions that maintain rich data structures that are shared among winagg functions. For example, a $histogram function could maintain a histogram data structure and min, max, median, ntile, rank could be implemented as O(1) or O(log n) reads from that data structure.

This is analogous to how avg is not computed directly, but is a quick computation from sum and count.

**Comment by vlsi** [comment]
Here's updated version.
Hope I'll finish windowed aggregates soon.

**Comment by vlsi** [comment]
The implementation is allmost finished. User-defined-aggregates are not yet working.
There are some failing tests, however window aggregation works like a charm.

@julianhyde , please have a look at the proposed APIs (`WinAggImplementor`, `AggImplementor`).

Here's generated code for `sum("commission") over (partition by "deptno" order by "empid" desc nulls first) as rcnf`
Basically, it never falls back to the full inner for-loop computation, and it just adds new rows to the already computed sum.

``` java
final java.util.Comparator _keyComparator0 = net.hydromatic.linq4j.function.Functions.nullsComparator(true, true);
long a0s0w0;
long a0w0 = 0L;
a0s0w0 = 0L;
int a1s0w0;
Integer a1w0 = (Integer) null;
a1s0w0 = 0;
while (iterator.hasNext()) {
  final Object[] _rows = (Object[]) iterator.next();
  prevStart = -1;
  prevEnd = 2147483647;
  for (int i = 0; i < _rows.length; ++i) {
    final Object[] row = (Object[]) _rows[i];
    final int end = net.hydromatic.optiq.runtime.BinarySearch.upperBound(_rows, i, _rows.length - 1, ((Integer) row[0]).intValue(), _keySelector0, _keyComparator0);
    if (end != prevEnd) {
      int actualStart;
      if (end < prevEnd) {
        actualStart = 0;
        a0s0w0 = 0L;
        a1s0w0 = 0;
      } else {
        actualStart = prevEnd + 1;
      }
      prevEnd = end;
      {
        for (int j = actualStart; j <= end; ++j) {
          final Integer inp2_ = (Integer) ((Object[]) _rows[j])[2];
          if (inp2_ != null) {
            a0s0w0++;
          }
          if (inp2_ != null) {
            a1s0w0 = a1s0w0 + inp2_.intValue();
          }
        }
        a0w0 = a0s0w0;
        a1w0 = (Integer) a1s0w0;
      }
    }
    _list.add(new Object[] {
      row[0],
      row[1],
      row[2],
      a0w0,
      a1w0});
  }
}
```

`WinAggImplementor`: https://github.com/vlsi/optiq/blob/3107b26eadb5ab57c7b044d84e6c85a84e5eaa76/core/src/main/java/net/hydromatic/optiq/rules/java/WinAggImplementor.java

`AggImplementor`: https://github.com/vlsi/optiq/blob/3107b26eadb5ab57c7b044d84e6c85a84e5eaa76/core/src/main/java/net/hydromatic/optiq/rules/java/AggImplementor.java

`rank()`: https://github.com/vlsi/optiq/blob/3107b26eadb5ab57c7b044d84e6c85a84e5eaa76/core/src/main/java/net/hydromatic/optiq/rules/java/RexImpTable.java#L1058

`first_value()`: https://github.com/vlsi/optiq/blob/3107b26eadb5ab57c7b044d84e6c85a84e5eaa76/core/src/main/java/net/hydromatic/optiq/rules/java/RexImpTable.java#L1110

`row_number()`: https://github.com/vlsi/optiq/blob/3107b26eadb5ab57c7b044d84e6c85a84e5eaa76/core/src/main/java/net/hydromatic/optiq/rules/java/RexImpTable.java#L1129

`count()` (works in both aggregate and window aggregate context): https://github.com/vlsi/optiq/blob/3107b26eadb5ab57c7b044d84e6c85a84e5eaa76/core/src/main/java/net/hydromatic/optiq/rules/java/RexImpTable.java#L912

etc.

**Comment by vlsi** [comment]
Now the implementation is feature-complete.
To do: correct javadocs and deal with `JavaRules.java:2114:5: Method length is 742 lines (max allowed is 390)` checkstyle error.

Notable improvements:
- Full window clause support
- Custom user-defined window aggregates might work (`ImplementableAggFunction` -> `getImplementor` -> `WinAggImplementor`), however not tested. I guess it is possible to implement lead/lag/ntile/row_number/rank as user-defined functions.
- Stateful aggregate function when using user-defined non-static aggregate. For instance, you can have `List` in the agg impl instance and join when the result is required. 
- Improved the performance of window function calculation: if the lower bound is not changed and the upper bound just increases, optiq reuses previously calculated aggregates.
  For instance, in case of `sum(salary) over (partition by deptno)` the actual count is calculated just once per department.
- Eliminated for-loop in window aggregate calculation if it is not required (e.g. `count(non_nullable_column)` or `row_number()` or similar do not require for-loop)
- Removed error 'Window has negative size'. The calculation machinery just treats those like empty windows. I think this is helpful for machine-generated queries
- Removed error 'first_value requires order by'. Oracle/PostgreSQL allow you to shoot in the foot like that, thus why don't we do the same?

**Comment by julianhyde** [comment]
I have reviewed https://github.com/vlsi/optiq/commit/33c9247db2a3585f04717e87801d772795000445 and it looks good to go.

Looks like your merge commit https://github.com/julianhyde/optiq/commit/e69714f92c19fb956e797229cafc6303ac011b0d had some issues in travis-ci. Can I re-do this as a rebase of https://github.com/julianhyde/optiq/commit/e300bf1b217a7a3fbdae2796add3b7fe610aee6e onto master?

**Comment by vlsi** [comment]
> /home/travis/build/julianhyde/optiq/plus/src/test/java/net/hydromatic/optiq/impl/tpcds/TpcdsTest.java:27: Wrong order for 'java.util.Random' import.

Is TpcdsTest expected to work?
I rolled back the rebase as I expect some more work in Tpcds

**Comment by vlsi** [comment]
I've updated import order in Tpcds tests and rebased this PR onto master

**Pull request merged**
