### PR TITLE
OPTIQ-101: First pass at interfaces for component access

### PR DESCRIPTION
**Pull request by jacques-n**
First pass at interfaces for Optiq component access.  PlannerInstance is an abstract class here but would probably actually be an implementation class in the final version of this task.

### CODE REVIEW

**Comment by julianhyde** [comment]
I've started integrating this and writing tests. 
1. I'm going to rename PlannerInstance to Planner. (Every object is an instance.)
2. Does parse just parse, or does it parse and validate? Does toRel validate its SqlNode argument before translating to RelNode?
3. It's not possible to create a schema without a root schema, and it's not possible to create a root schema without a connection.

So, I propose changing the API so that rather than passing in a root schema to createPlanner, the planner creates its own, and then the caller calls PlannerInstance.getRootSchema().

``` java
Planner planner = Planner.getPlanner(SqlStdOperatorTable.instance(), new MyRule());
Schema schema = MapSchema.create(planner.getRootSchema(), "hr");
planner.setSchema(schema);
SqlNode node = planner.parse("select * from emps");
```

Does that fit how you intend to use this API?

**Comment by julianhyde** [comment]
You can see the latest at https://github.com/julianhyde/optiq/tree/optiq-101.

**Comment by jacques-n** [comment]
> I've started integrating this and writing tests.

Great!

**Comment by julianhyde** [comment]
I incorporated most of this in my my fix to https://github.com/julianhyde/optiq/issues/101, commit https://github.com/julianhyde/optiq/commit/dd44259294363045985cf2bf4e017a410c8c143f. I removed explain() -- it does not do much at the RelNode level -- and I added an explicit validate() and renamed toRel() to convert().

**Pull request closed without merging**
